# Generated by Django 5.0.6 on 2024-10-15 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iActivitiesId', models.IntegerField(auto_created=True, unique=True)),
                ('dAddedDate', models.DateField(null=True)),
                ('dAddedDateTime', models.DateTimeField(null=True)),
                ('tActivityParams', models.TextField(null=True)),
                ('tExtraParams', models.TextField(null=True)),
                ('iSystemDeleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='activityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iActivityMasterId', models.IntegerField(auto_created=True, unique=True)),
                ('cActivityMasterName', models.CharField(max_length=256)),
                ('cActivityMasterCode', models.CharField(max_length=256, unique=True)),
                ('cActivityConfig', models.CharField(max_length=256, unique=True)),
                ('eStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=256)),
                ('dAddedDate', models.DateField(null=True)),
                ('dUpdatedDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='activityTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iActivityTypeMasterID', models.IntegerField(auto_created=True, unique=True)),
                ('cActivityType', models.CharField(max_length=256, null=True)),
                ('cActivityCode', models.CharField(max_length=256, null=True)),
                ('eStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='activityEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iActivityEntityID', models.IntegerField(auto_created=True, unique=True)),
                ('dAddedDate', models.DateField()),
                ('dAddedDateTime', models.DateTimeField()),
                ('cEntity', models.CharField(max_length=216)),
                ('iEntityId', models.IntegerField()),
                ('iActivitiesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activities', to_field='iActivitiesId')),
            ],
        ),
        migrations.CreateModel(
            name='activityMasterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iActivityMasterTemplate', models.IntegerField(auto_created=True, unique=True)),
                ('cActivityTempalte', models.CharField(max_length=512, null=True)),
                ('eLanguage', models.CharField(choices=[('en', 'en'), ('fr', 'fr')], max_length=216)),
                ('iActivityMasterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitymaster')),
            ],
        ),
    ]
