# Generated by Django 5.0.6 on 2024-10-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='iActivitiesId',
            field=models.IntegerField(auto_created=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activitytypemaster',
            name='iActivityTypeMasterID',
            field=models.IntegerField(auto_created=True, null=True, unique=True),
        ),
    ]
