# Generated by Django 5.0.6 on 2024-10-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activities_iactivitiesid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytypemaster',
            name='iActivityTypeMasterID',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
