# Generated by Django 5.0.6 on 2024-10-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitytypemaster_iactivitytypemasterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytypemaster',
            name='id',
        ),
        migrations.AlterField(
            model_name='activitytypemaster',
            name='iActivityTypeMasterID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
