# Generated by Django 5.0.6 on 2024-10-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_activitytypemaster_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activityentity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activitymaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activitymastertemplate',
            name='id',
        ),
        migrations.AlterField(
            model_name='activities',
            name='iActivitiesId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activityentity',
            name='iActivitiesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activities'),
        ),
        migrations.AlterField(
            model_name='activityentity',
            name='iActivityEntityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activitymaster',
            name='iActivityMasterId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activitymastertemplate',
            name='iActivityMasterTemplate',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
