# Generated by Django 5.0.6 on 2024-10-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_activities_id_remove_activityentity_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityentity',
            old_name='iActivityEntityID',
            new_name='iActivityEntityId',
        ),
    ]
