# Generated by Django 5.0.6 on 2024-10-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_rename_iactivityentityid_activityentity_iactivityentityid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitymastertemplate',
            old_name='iActivityMasterTemplate',
            new_name='iActivityMasterTemplateID',
        ),
    ]
