# Generated by Django 5.0.6 on 2024-10-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_rename_iactivitymastertemplate_activitymastertemplate_iactivitymastertemplateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymastertemplate',
            name='cActivityTempalte',
        ),
        migrations.AlterField(
            model_name='activitymastertemplate',
            name='eLanguage',
            field=models.CharField(choices=[('en', 'en'), ('fr', 'fr')], default='en', max_length=216),
        ),
    ]
