# Generated by Django 5.0.6 on 2024-10-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_remove_activitymastertemplate_cactivitytempalte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymastertemplate',
            name='tActivityTempalte',
            field=models.TextField(null=True),
        ),
    ]
