# Generated by Django 5.0.6 on 2024-10-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activitymastertemplate_tactivitytempalte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymaster',
            name='cActivityConfig',
        ),
    ]
