# Generated by Django 5.0.6 on 2024-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_remove_activitymaster_cactivityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymaster',
            name='tActivityConfig',
            field=models.TextField(default='', max_length=256, unique=True),
        ),
    ]
