# Generated by Django 5.0.6 on 2024-10-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activitymaster_tactivityconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymaster',
            name='tActivityConfig',
            field=models.TextField(default='', max_length=256),
        ),
    ]
