# Generated by Django 5.0.6 on 2024-10-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activitymaster_tactivityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='iActivityForId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='iActivityMasterID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='activity.activitymaster'),
        ),
        migrations.AddField(
            model_name='activities',
            name='iActivityTypeMasterID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='activity.activitytypemaster'),
        ),
    ]
