# Generated by Django 5.0.6 on 2024-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activities_iactivityforid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymaster',
            name='cActivityMasterCode',
            field=models.CharField(max_length=256),
        ),
    ]
