# Generated by Django 5.0.6 on 2024-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_alter_activitymastertemplate_elanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymastertemplate',
            name='eLanguage',
            field=models.CharField(choices=[('En', 'En'), ('Fr', 'fr')], default='en', max_length=216),
        ),
    ]
